-- Baseline schema generated from current JPA entities (Hibernate 7 / PostgreSQL).
-- Flyway owns DDL; spring.jpa.hibernate.ddl-auto=validate checks this stays in sync.
-- Booking.site_postal_code is a Hibernate @Formula, not a column.

create table ai_recommendations (id bigint generated by default as identity, ai_reasoning_summary TEXT, confidence_score numeric(10,2), correlation_id varchar(255), created_at timestamp(6) not null, document_url varchar(255), expected_budget_amount numeric(19,2), expected_budget_currency varchar(255), expected_budget_source varchar(255), haystack_user_id varchar(255), idempotency_key varchar(255), ingest_id varchar(255), raw_project_prompt TEXT, status varchar(255) check ((status in ('GENERATED','ACCEPTED','REJECTED','EXPIRED'))), tentative_end_date date, tentative_start_date date, warnings TEXT, previous_recommendation_id bigint, user_id bigint, primary key (id));

create table asset_categories (id bigint generated by default as identity, description varchar(255), name varchar(100) not null unique, primary key (id));

create table asset_images (id bigint generated by default as identity, image TEXT, uploaded_at timestamp(6) not null, asset_id bigint not null, primary key (id));

create table assets (id bigint generated by default as identity, base_daily_rate numeric(10,2) not null, capacity integer, condition varchar(255) check ((condition in ('EXCELLENT','GOOD','FAIR','NEEDS_REPAIR'))), description varchar(255), last_condition_updated_at timestamp(6), location varchar(100), max_daily_rate numeric(10,2) not null, min_daily_rate numeric(10,2) not null, name varchar(100) not null unique, platform_height numeric(10,2), purchase_year integer, serialno varchar(255) not null, category_id bigint not null, primary key (id));

create table booking_items (id bigint generated by default as identity, daily_rate numeric(38,2), end_engine_hours numeric(38,2), initial_condition varchar(255) check ((initial_condition in ('EXCELLENT','GOOD','FAIR','NEEDS_REPAIR'))), return_condition varchar(255) check ((return_condition in ('EXCELLENT','GOOD','FAIR','NEEDS_REPAIR'))), start_engine_hours numeric(38,2), subtotal numeric(38,2), asset_id bigint, booking_id bigint, primary key (id));

create table bookings (id bigint generated by default as identity, balance_charge_attempted_at timestamp(6), created_at timestamp(6), delivery_notes varchar(500), deposit_amount numeric(38,2), end_date date, needs_manual_follow_up boolean default false, remaining_balance numeric(38,2), return_notes varchar(500), site_address varchar(255), site_latitude numeric(38,2), site_longitude numeric(38,2), start_date date, status varchar(255) check ((status in ('PENDING_DEPOSIT','PENDING_CONFIRMED','CONFIRMED','MOBILISED','COMPLETED','CANCELLED'))), total_amount numeric(38,2), customer_id bigint, rental_plan_id bigint, primary key (id));

create table delivery_records (id bigint generated by default as identity, customer_signature_url varchar(255), delivered_at timestamp(6), delivery_photos varchar(255), booking_id bigint, driver_id bigint, primary key (id));

create table payments (id bigint generated by default as identity, amount numeric(38,2), created_at timestamp(6), failure_reason varchar(255), manual_follow_up_reason varchar(255), paid_at timestamp(6), payment_type varchar(255) check ((payment_type in ('DEPOSIT','BALANCE','FULL_PAYMENT'))), requires_manual_follow_up boolean default false, status varchar(255) check ((status in ('PENDING','SUCCESS','FAIL'))), stripe_charge_id varchar(255), stripe_customer_id varchar(255), stripe_payment_intent_id varchar(255), stripe_payment_method_id varchar(255), booking_id bigint, primary key (id));

create table recommendation_items (id bigint generated by default as identity, match_score numeric(38,2), ml_predicted_price numeric(38,2), rank_order integer, asset_id bigint, recommendation_id bigint, primary key (id));

create table rental_plan (id bigint generated by default as identity, created_at timestamp(6), end_date date, site_address varchar(255), site_latitude numeric(38,2), site_longitude numeric(38,2), site_postal_code varchar(255), start_date date, status varchar(255) check ((status in ('DRAFT','SAVED','QUOTED','CONVERTED','CANCELLED'))), total_amount numeric(38,2), updated_at timestamp(6), version bigint not null, customer_id bigint not null, primary key (id));

create table rental_plan_records (id bigint generated by default as identity, daily_rate numeric(38,2), subtotal numeric(38,2), asset_id bigint, rental_plan_id bigint, primary key (id));

create table return_records (id bigint generated by default as identity, customer_signature_url varchar(255), return_photos varchar(255), returned_at timestamp(6), booking_id bigint, driver_id bigint, primary key (id));

create table users (id bigint generated by default as identity, company varchar(255), created_at timestamp(6), email varchar(255), enabled boolean not null, name varchar(100) not null unique, password varchar(255) not null, role varchar(20) not null check ((role in ('USER','ADMIN','DRIVER'))), stripe_customer_id varchar(255), primary key (id));

alter table if exists ai_recommendations add constraint FKc1vhy3akthqmwdn1mtjqpk400 foreign key (previous_recommendation_id) references ai_recommendations;

alter table if exists ai_recommendations add constraint FKawyie1nntxfgm46oh0tdk91q5 foreign key (user_id) references users;

alter table if exists asset_images add constraint FKla3ikxm0m4arxt9733q0ytwrw foreign key (asset_id) references assets;

alter table if exists assets add constraint FKcwxkksxvxtrvv0sjtu5cgflep foreign key (category_id) references asset_categories;

alter table if exists booking_items add constraint FKphe2hayjg09iuxoc0ae6wbm02 foreign key (asset_id) references assets;

alter table if exists booking_items add constraint FKrw74irmyat5c39cnjkn02u99m foreign key (booking_id) references bookings;

alter table if exists bookings add constraint FKib6gjgj2e9binkktxmm175bmm foreign key (customer_id) references users;

alter table if exists bookings add constraint FK211tj9ycvdwqolxlc55i8i8bm foreign key (rental_plan_id) references rental_plan;

alter table if exists delivery_records add constraint FKninktq8pmsu84vkujasvgvqvr foreign key (booking_id) references bookings;

alter table if exists delivery_records add constraint FKndqt8yqoxvpgs2argfh7swn9x foreign key (driver_id) references users;

alter table if exists payments add constraint FKc52o2b1jkxttngufqp3t7jr3h foreign key (booking_id) references bookings;

alter table if exists recommendation_items add constraint FKaus8kg86g5cqt9d4netttyij6 foreign key (asset_id) references assets;

alter table if exists recommendation_items add constraint FK5p3rr2fvlqjymhdims7tqyca3 foreign key (recommendation_id) references ai_recommendations;

alter table if exists rental_plan add constraint FKeecin3ax9s4434cpnuby1n39e foreign key (customer_id) references users;

alter table if exists rental_plan_records add constraint FK77qagmx2uaqku9epknhn2u38t foreign key (asset_id) references assets;

alter table if exists rental_plan_records add constraint FK9oyah7tg5p681j31vn29yua22 foreign key (rental_plan_id) references rental_plan;

alter table if exists return_records add constraint FKmaqygw85es6i4d7d7h3ljn31j foreign key (booking_id) references bookings;

alter table if exists return_records add constraint FKsok8lbshbpv2gaf3ykjq1tkx6 foreign key (driver_id) references users;

